### ISSUE TITLE
Consider the license from GNU to MIT?

### ISSUE THREAD

**Issue by shunchu** [jonathanKingston/ember-cli-chai#1]
Hi Thanks for this wonderful Ember-CLI addon. Just a word on license: Most companies that build closed-source enterprise apps will not allow use of GNU licensed software used for development (I'm just a messenger). Having something more liberal like MIT or Apache2 is usually looked upon as more favorable. If you feel that this request is inappropriate or inconsistent with your belief on how software should be shared, feel free to close this issue. But I just wanted to point this out. Cheers! :beer:

**Comment by jonathanKingston** [comment]
@shunchu thank you for your ticket.

I'm far from an expert with licences (I need to make the default MIT in the package JSON match), however I have always put LGPL 3 licenses on my code after carefully reviewing the modern licences a while back for the following reasons:
- Code can be linked from as a library by closed source applications
- Modifications to the library go back to the community
- Licenses always have to remain for all derivative work

LGPL 3 to my understanding is basically Apache2 for closed source enterprise applications besides they have to make the choice of:
- Committing back to the community any modifications
- Using the code as a library only

For a front end testing library like this, disclosure of using it shouldn't impact the companies security. I get that companies are wary of using licenses that are not as open as possible however I really do feel that corporates shouldn't be looking to piggyback from peoples time without committing back bug fixes.

Perhaps I am on a losing battle, feel free to share your opinions here.

**Comment by shunchu** [comment]
Hey @jonathanKingston, the code is yours. Feel free to do what you feel is right with it. I used to work for a Fortune 500 company that would not allow code to be used for even internal projects if the license wasn't BSD, MIT, Apache2 or something along those lines. I'm no licensing expert... just want to bring this up. But it looks like you've done some research on it already.

Also, your npmjs.com licensing still says "MIT" license. So whatever you decide, you might want to change that as well.

**Comment by jonathanKingston** [comment]
@shunchu yeah I was aware of the mismatch, I have swapped it over to MIT as I'm not really to bothered about this project, it is mostly just to get ember working with Chai for my own purposes.

Thank you for raising.
