### ISSUE TITLE
error upon install

### ISSUE THREAD

**Issue by mgenev** [jonathanKingston/ember-cli-chai#2]
running `ember install:addon ember-cli-chai`

gives me:
```
client|master⚡ ⇒ ember install:addon ember-cli-chai
version: 0.2.2

A new version of ember-cli is available (0.2.3). To install it, type ember update.
Installed packages for tooling via npm.
The package `ember-cli-chai` is not a properly formatted package, we have used a fallback lookup to resolve it at `/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-chai`. This is generally caused by an addon not having a `main` entry point (or `index.js`).
The `ember-cli-chai` addon could not be found at `/Users/martin.genev/Projects/how-to/client/node_modules/ember-cli-chai`.
```

**Comment by jonathanKingston** [comment]
Ah yeah it's a new change in ember-cli. Will fix, thanks for reporting.

Running `npm --save-dev ember-cli-chai` should install it for now, the warning will appear still though.

**Comment by mgenev** [comment]
simply having `"ember-cli-chai": "0.0.5", ` in my `package.json` and then running `ember test` gives me the same error and the tests won't run :-/

**Comment by jonathanKingston** [comment]
Hmm yeah wasn't what I thought it was at all, published a new but I think npm might have got corrupted at the last release. Going to try forcing the index to change.

**Comment by jonathanKingston** [comment]
@mgenev looks fixed now and the other error has gone with 0.0.6.

@isaacs do you still get these partial corrupt packages on the server side? I have not seen the symptom in a long time. npm cache clean and clearing everything didn't fix it, nor did updating the package. I made a change in the missing index.js and all now seems ok in 0.0.7.

**Comment by mgenev** [comment]
Now I can install it and run the tests, thanks for the quick fix.

However when I `import { expect } from 'chai';` the test fails saying `Can't find variable: chai `

**Comment by jonathanKingston** [comment]
I have no idea what is causing the index.js to go missing, it happened again after fixing the issue you mentioned.
The file is valid but when installing it doesn't get pulled down, I need to investigate that further as I'm not seeing the behaviour on any other of my repos.

Anyway issue should be resolved now fingers crossed. Tests must be written for this but for now I am of to bed.

**Comment by mgenev** [comment]
it just worked! thanks a lot
